export const messages = {
    //رسائل
    required: `هذا الحقل إلزامي `,
    arabic: `الكتابة باللغة العربية فقط`,
    remote: `يرجى تصحيح هذا الحقل للمتابعة`,
    trim: `احذف المسافات في أول وأخر الكلمة`,
    email: `رجاء إدخال عنوان بريد إلكتروني صحيح`,
    url: `رجاء إدخال عنوان موقع إلكتروني صحيح`,
    date: `رجاء إدخال تاريخ صحيح`,
    dateISO: `رجاء إدخال تاريخ صحيح (ISO)`,
    number: `رجاء إدخال عدد بطريقة صحيحة`,
    digits: `رجاء إدخال أرقام فقط`,
    creditcard: `رجاء إدخال رقم بطاقة ائتمان صحيح`,
    equalTo: `رجاء إدخال نفس القيمة`,
    equalToNum: (num) => `يجب أن يكون  ${num} رقما بالضبط `,
    extension: (extension) => `رجاء إدخال ملف بامتداد ${extension}`,
    maxlength: (maxlength) => `الحد الأقصى لعدد الحروف هو ${maxlength}`,
    minlength: (minlength) => `الحد الأدنى لعدد الحروف هو ${minlength}`,
    rangelength: (minlength, maxlength) =>
      `عدد الحروف يجب أن يكون بين ${minlength} و ${maxlength}`,
    range: (min, max) => `رجاء إدخال عدد قيمته بين ${min} و ${max}`,
    rangeLength: (min, max) => `عدد الارقام يجب أن يكون بين ${min} و ${max}`,
    rangeDate: (min, max) => `رجاء إدخال تاريخ بين ${min} و ${max}`,
    max: (max) => `رجاء إدخال عدد أقل من أو يساوي ${max}`,
    min: (min) => `رجاء إدخال عدد أكبر من أو يساوي ${min}`,
  };
  
  export const structureInfo = {
    //هيكل معلومات
    civilStatus: {
      fname: "الاسم",
      lname: "اللقب",
      fname_fr: "الاسم بالاتينية",
      lname_fr: "اللقب بالاتينية",
      gender: "الجنس",
      yearBirthRegistry: "سنة التسجيل في سجل الولادات",
      bornJudgment: "مولود بحكم",
      birthContract: "عقد الميلاد",
      dateOfBirth: "تاريخ الميلاد",
      birthContractNumber: "رقم شهادة الميلاد",
      BirthRecordSerialNumber: "الرقم التسلسلي لسجل المواليد",
      CountryOfBirth: "بلد الميلاد",
      birthState: "ولاية الميلاد",
      AdministrativeService: "دائرة الميلاد",
      birthMunicipality: "بلدية الميلاد",
      placeOfBirth: "مكان الميلاد",
      placeOfBirth_fr: "مكان الميلاد بالاتينية",
      dualNnationality: "مزدوج الجنسية ",
      Nationality: "الجنسية",
      acquiredNationality: "الجنسية المكتسبة",
      NameFather: "اسم الأب",
      motherFname: "اسم الأم",
      motherLname: "لقب الأم",
    },
    schoolStatus: {
      registrationNumSchool: "رقم القيد",
      schoolRegistrationDate: "تاريخ التسجيل",
      RegisteredWithExceptionalLicense: "مسجل برخصة استثنائية",
      FailCurrentYear: "معيد السنة الحالية",
      preparatoryEducation: "هل استفادة من التربية التحضيرية؟",
      benefit: "طبيعة الاستفادة (اذا كان نعم):",
  
      schoolSystem: "نظام التمدرس",
      physicalEducation: "معفى من التربية البدنية ؟",
      ArtEducation: "التربية الفنية (إن وجدت)؟",
      FreeBooks: "مستفيد من مجانية الكتب ؟",
      BeneficiaryRestaurant: "مستفيد من المطعم ؟",
      BeneficiaryTransportation: "مستفيد من النقل المدرسي ؟",
      distance_home_school: "المسافة بين البيت والمدرسة ",
      TransportationUsed: "وسيلة النقل المستعملة",
      Time_home_school: "الوقت المستغرق من البيت الى المدرسة",
      beneficiary_3000: "مستفيد من منحة 3000 ؟",
      natureStudy: "طبيعة الدراسة",
      Business_oriented: "فوج الاعمال الموجهة ؟",
    },
    level: "السنة",
    class: "القسم",
  
    schoolId: "رقم التعريف المدرسي",
  
    Family: "درجة القرابة",
  };
  export const option = {
    gender: {
      m: "ذكر",
      f: "أنثى",
    },
    judging: {
      no: "لا",
      yes: "نعم",
    },
    classa: {
      1: 1,
      2: 2,
    },
    schoolSystem: {
      internal: "داخلي",
      halfInner: "نصف داخلي",
      externa: "خارجي",
    },
    level: {
      0: "تحضيري",
      1: "أولى",
      2: "ثانية",
      3: "ثالثة",
      4: "رابعة",
      5: "خامسة",
    },
    birthContract: {
      normal: "عادي",
      repeater: "مكرر",
      repeater_1: "مكرر 1",
      repeater_2: "مكرر 2",
      unregistered: "غير مسجل",
    },
    benefit: {
      publicSchool: "مدرسة عمومية",
      PrivateSchool: "مدرسة خاصة",
      QuranicSchool: "مدرسة قرآنية",
      publicKindergarten: "روضة عمومية",
      privateKindergarten: "روضة خاصة",
    },
  };
  